spring:
  application:
    name: database
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tagbiometrictest}
    username: ${DB_USERNAME:tagdev}
    password: ${DB_PASSWORD:tagdev}
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
    enabled: ${LIQUIBASE_ENABLED:false}
