ALTER TABLE client DROP COLUMN IF EXISTS bin;
ALTER TABLE client_aud DROP COLUMN IF EXISTS bin;

ALTER TABLE card_product ADD COLUMN IF NOT EXISTS bin VARCHAR(9);
ALTER TABLE card_product_aud ADD COLUMN IF NOT EXISTS bin VARCHAR(9);